# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main  # or the branch you want to trigger the pipeline

pool:
  name: Self-Hosted agent pool
  demands:
    - agent.name -equals Self-Hosted agent pool

variables:
  dockerRegistryServiceConnection: 'Docker Hub Repo'
  imageRepository: 'navinjohn/flask_docker'
  dockerfilePath: 'Dockerfile'
  tag: 'latest'
  dockerUsername: 'Navinjohn'
  dockerPassword: 'Navinjohn@08'

steps:
- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: '$(imageRepository)'
    command: 'buildAndPush'
    Dockerfile: '$(dockerfilePath)'
    tags: |
      $(tag)

- task: Docker@2
  displayName: 'Logout from Docker Registry'
  inputs:
    command: 'logout'
    containerRegistry: '$(dockerRegistryServiceConnection)'

- script: |
    echo "Running Docker container on Docker Desktop"
    docker login -u $(dockerUsername) -p $(dockerPassword)
    docker pull $(imageRepository):$(tag)
    docker stop $(imageRepository) || true
    docker rm $(imageRepository) || true
    docker run --name $(imageRepository) -d -p 80:80 $(imageRepository):$(tag)
  displayName: 'Run Docker container on Docker Desktop'
  env:
    DOCKER_HOST: 'tcp://host.docker.internal:2375'
    DOCKER_TLS_VERIFY: '0'
    dockerUsername: $(dockerUsername)
    dockerPassword: $(dockerPassword)
